export const europeanFootballTeams = [
  // EPL (English Premier League)
  {
    name: "Manchester United",
    league: "EPL",
    europeanTitles: 3,
    mostFamousCoach: "Sir Alex Ferguson",
    highestVictory: "10-0 vs Anderlecht (1956)",
    highestDefeat: "0-7 vs Liverpool (2023)",
  },
  {
    name: "Liverpool",
    league: "EPL",
    europeanTitles: 6,
    mostFamousCoach: "Bill Shankly",
    highestVictory: "11-0 vs Stromsgodset (1974)",
    highestDefeat: "1-9 vs Birmingham City (1954)",
  },
  {
    name: "Chelsea",
    league: "EPL",
    europeanTitles: 2,
    mostFamousCoach: "José Mourinho",
    highestVictory: "13-0 vs Jeunesse Hautcharage (1971)",
    highestDefeat: "1-8 vs Wolverhampton Wanderers (1953)",
  },
  {
    name: "Arsenal",
    league: "EPL",
    europeanTitles: 1,
    mostFamousCoach: "Arsène Wenger",
    highestVictory: "12-0 vs Loughborough (1900)",
    highestDefeat: "0-8 vs Loughborough (1896)",
  },
  {
    name: "Manchester City",
    league: "EPL",
    europeanTitles: 1,
    mostFamousCoach: "Pep Guardiola",
    highestVictory: "10-0 vs Huddersfield Town (1987)",
    highestDefeat: "0-8 vs Burton Albion (2019)",
  },

  // Serie A
  {
    name: "AC Milan",
    league: "Serie A",
    europeanTitles: 7,
    mostFamousCoach: "Arrigo Sacchi",
    highestVictory: "13-0 vs Audax Modena (1914)",
    highestDefeat: "0-8 vs Bologna (1950)",
  },
  {
    name: "Juventus",
    league: "Serie A",
    europeanTitles: 2,
    mostFamousCoach: "Giovanni Trapattoni",
    highestVictory: "15-0 vs Cento (1927)",
    highestDefeat: "0-7 vs AC Milan (1950)",
  },
  {
    name: "Inter Milan",
    league: "Serie A",
    europeanTitles: 3,
    mostFamousCoach: "Helenio Herrera",
    highestVictory: "16-0 vs Milan (1915)",
    highestDefeat: "0-9 vs Juventus (1961)",
  },
  {
    name: "AS Roma",
    league: "Serie A",
    europeanTitles: 0,
    mostFamousCoach: "Fabio Capello",
    highestVictory: "9-0 vs Cremonese (1929)",
    highestDefeat: "1-7 vs Manchester United (2007)",
  },
  {
    name: "Napoli",
    league: "Serie A",
    europeanTitles: 1,
    mostFamousCoach: "Diego Maradona (as an influence)",
    highestVictory: "8-0 vs Pro Patria (1955)",
    highestDefeat: "0-8 vs Torino (1951)",
  },

  // La Liga
  {
    name: "Real Madrid",
    league: "La Liga",
    europeanTitles: 14,
    mostFamousCoach: "Miguel Muñoz",
    highestVictory: "11-1 vs Elche (1960)",
    highestDefeat: "0-8 vs Espanyol (1930)",
  },
  {
    name: "Barcelona",
    league: "La Liga",
    europeanTitles: 5,
    mostFamousCoach: "Pep Guardiola",
    highestVictory: "12-1 vs Badalona (1932)",
    highestDefeat: "1-12 vs Athletic Bilbao (1931)",
  },
  {
    name: "Atlético Madrid",
    league: "La Liga",
    europeanTitles: 0,
    mostFamousCoach: "Diego Simeone",
    highestVictory: "9-0 vs Real Oviedo (1958)",
    highestDefeat: "0-8 vs Espanyol (1957)",
  },
  {
    name: "Sevilla",
    league: "La Liga",
    europeanTitles: 0,
    mostFamousCoach: "Juande Ramos",
    highestVictory: "10-0 vs Figueroa (1940)",
    highestDefeat: "2-8 vs Real Madrid (1958)",
  },
  {
    name: "Valencia",
    league: "La Liga",
    europeanTitles: 0,
    mostFamousCoach: "Rafa Benítez",
    highestVictory: "8-0 vs Sporting Gijón (1944)",
    highestDefeat: "0-9 vs Barcelona (1950)",
  },

  // Ligue 1
  {
    name: "Paris Saint-Germain",
    league: "Ligue 1",
    europeanTitles: 0,
    mostFamousCoach: "Laurent Blanc",
    highestVictory: "10-0 vs Côte Chaude (2014)",
    highestDefeat: "1-6 vs Juventus (1997)",
  },
  {
    name: "Marseille",
    league: "Ligue 1",
    europeanTitles: 1,
    mostFamousCoach: "Raymond Goethals",
    highestVictory: "20-2 vs Stade Helvétique Marseille (1943)",
    highestDefeat: "1-8 vs RC Paris (1953)",
  },
  {
    name: "Lyon",
    league: "Ligue 1",
    europeanTitles: 0,
    mostFamousCoach: "Gérard Houllier",
    highestVictory: "10-0 vs Ajaccio (1953)",
    highestDefeat: "1-8 vs Sochaux (1954)",
  },
  {
    name: "Monaco",
    league: "Ligue 1",
    europeanTitles: 0,
    mostFamousCoach: "Didier Deschamps",
    highestVictory: "9-0 vs Girondins Bordeaux (1986)",
    highestDefeat: "1-9 vs PSG (2019)",
  },
  {
    name: "Saint-Étienne",
    league: "Ligue 1",
    europeanTitles: 0,
    mostFamousCoach: "Robert Herbin",
    highestVictory: "10-1 vs Sochaux (1957)",
    highestDefeat: "0-7 vs Lyon (1969)",
  },

  // Bundesliga
  {
    name: "Bayern Munich",
    league: "Bundesliga",
    europeanTitles: 6,
    mostFamousCoach: "Franz Beckenbauer",
    highestVictory: "16-1 vs Waldberg (1997)",
    highestDefeat: "0-7 vs Schalke (1976)",
  },
  {
    name: "Borussia Dortmund",
    league: "Bundesliga",
    europeanTitles: 1,
    mostFamousCoach: "Jürgen Klopp",
    highestVictory: "11-1 vs Arminia Bielefeld (1982)",
    highestDefeat: "0-12 vs Borussia Mönchengladbach (1978)",
  },
  {
    name: "Schalke 04",
    league: "Bundesliga",
    europeanTitles: 0,
    mostFamousCoach: "Huub Stevens",
    highestVictory: "20-0 vs FC Marnheim (1940)",
    highestDefeat: "0-11 vs Borussia Dortmund (1940)",
  },
  {
    name: "Borussia Mönchengladbach",
    league: "Bundesliga",
    europeanTitles: 0,
    mostFamousCoach: "Hennes Weisweiler",
    highestVictory: "12-0 vs Borussia Dortmund (1978)",
    highestDefeat: "0-7 vs VfB Stuttgart (1966)",
  },
  {
    name: "Bayer Leverkusen",
    league: "Bundesliga",
    europeanTitles: 0,
    mostFamousCoach: "Christoph Daum",
    highestVictory: "9-1 vs SSV Ulm (1999)",
    highestDefeat: "1-9 vs SpVgg Fürth (1940)",
  },
];
