// const text = [
//   `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
//   `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
//   `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
//   `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
//   `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
// I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
//   `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
//   `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
//   `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
//   `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
// ];
// export default text;
const text = [
  `God's love is everlasting, His grace infinite. Through faith in Jesus Christ, we are redeemed and given new life. Let us praise His holy name, for He is our Savior and Redeemer. In every trial, He is our refuge and strength. The Lord is our Shepherd, and we shall not want. Through His Word, we are guided on the path of righteousness.`,
  `Love your neighbor as yourself, for this is the greatest commandment. Walk in the light of Christ and let your actions reflect His love. Serve others humbly, for Christ came not to be served but to serve. In the body of Christ, we are all one, each part valuable and cherished.`,
  `For God so loved the world that He gave His only Son, that whoever believes in Him shall not perish but have eternal life. Christ is the light of the world, and through Him, darkness is overcome. Let us follow Him and be the light to others, reflecting His glory.`,
  `Rejoice in the Lord always, and again I say rejoice! The joy of the Lord is our strength. Let us give thanks in all circumstances, for this is God’s will for us in Christ Jesus. When we pray, we connect with the heart of our Father, and through prayer, our faith is strengthened.`,
  `The kingdom of God is like a mustard seed, which a man took and planted in his field. Though it is the smallest of all seeds, when it grows, it becomes the largest of garden plants. Likewise, our faith may start small, but with nurture and care, it can grow and bear much fruit.`,
  `The Word of God is living and active, sharper than any two-edged sword. It pierces the soul, dividing soul and spirit, joints and marrow, discerning the thoughts and intentions of the heart. Let us meditate on His Word day and night, for it is a lamp unto our feet and a light unto our path.`,
  `The Lord is my rock and my fortress, my deliverer in whom I trust. In times of trouble, I call upon His name, and He rescues me from the storms of life. His love endures forever, and His mercy is new every morning. Praise be to God, who hears the cries of His people.`,
  `In Christ, we are a new creation; the old has passed away, behold, the new has come! Let us put off our old selves, which belong to our former way of life, and be renewed in the spirit of our minds. Clothe yourselves with compassion, kindness, humility, gentleness, and patience.`,
  `Put on the full armor of God so that you can take your stand against the devil’s schemes. Our struggle is not against flesh and blood but against the rulers, authorities, and powers of this dark world. Stand firm, with the belt of truth buckled around your waist, and the shield of faith to extinguish all the flaming arrows of the evil one.`,
];
export default text;
