export const bibleBooks = [
  { number: 1, name: "Genesis", book: "Old Testament", author: "Moses" },
  { number: 2, name: "Exodus", book: "Old Testament", author: "Moses" },
  { number: 3, name: "Leviticus", book: "Old Testament", author: "Moses" },
  { number: 4, name: "Numbers", book: "Old Testament", author: "Moses" },
  { number: 5, name: "Deuteronomy", book: "Old Testament", author: "Moses" },
  { number: 6, name: "Joshua", book: "Old Testament", author: "Joshua" },
  {
    number: 7,
    name: "Judges",
    book: "Old Testament",
    author: "Samuel (traditionally attributed)",
  },
  {
    number: 8,
    name: "Ruth",
    book: "Old Testament",
    author: "Samuel (traditionally attributed)",
  },
  {
    number: 9,
    name: "1 Samuel",
    book: "Old Testament",
    author: "Samuel (traditionally attributed)",
  },
  {
    number: 10,
    name: "2 Samuel",
    book: "Old Testament",
    author: "Samuel (traditionally attributed)",
  },
  {
    number: 11,
    name: "1 Kings",
    book: "Old Testament",
    author: "Jeremiah (traditionally attributed)",
  },
  {
    number: 12,
    name: "2 Kings",
    book: "Old Testament",
    author: "Jeremiah (traditionally attributed)",
  },
  {
    number: 13,
    name: "1 Chronicles",
    book: "Old Testament",
    author: "Ezra (traditionally attributed)",
  },
  {
    number: 14,
    name: "2 Chronicles",
    book: "Old Testament",
    author: "Ezra (traditionally attributed)",
  },
  { number: 15, name: "Ezra", book: "Old Testament", author: "Ezra" },
  { number: 16, name: "Nehemiah", book: "Old Testament", author: "Nehemiah" },
  {
    number: 17,
    name: "Esther",
    book: "Old Testament",
    author: "Mordecai (traditionally attributed)",
  },
  {
    number: 18,
    name: "Job",
    book: "Old Testament",
    author: "Moses (traditionally attributed)",
  },
  {
    number: 19,
    name: "Psalms",
    book: "Old Testament",
    author: "David and others",
  },
  { number: 20, name: "Proverbs", book: "Old Testament", author: "Solomon" },
  {
    number: 21,
    name: "Ecclesiastes",
    book: "Old Testament",
    author: "Solomon",
  },
  {
    number: 22,
    name: "Song of Solomon",
    book: "Old Testament",
    author: "Solomon",
  },
  { number: 23, name: "Isaiah", book: "Old Testament", author: "Isaiah" },
  { number: 24, name: "Jeremiah", book: "Old Testament", author: "Jeremiah" },
  {
    number: 25,
    name: "Lamentations",
    book: "Old Testament",
    author: "Jeremiah",
  },
  { number: 26, name: "Ezekiel", book: "Old Testament", author: "Ezekiel" },
  { number: 27, name: "Daniel", book: "Old Testament", author: "Daniel" },
  { number: 28, name: "Hosea", book: "Old Testament", author: "Hosea" },
  { number: 29, name: "Joel", book: "Old Testament", author: "Joel" },
  { number: 30, name: "Amos", book: "Old Testament", author: "Amos" },
  { number: 31, name: "Obadiah", book: "Old Testament", author: "Obadiah" },
  { number: 32, name: "Jonah", book: "Old Testament", author: "Jonah" },
  { number: 33, name: "Micah", book: "Old Testament", author: "Micah" },
  { number: 34, name: "Nahum", book: "Old Testament", author: "Nahum" },
  { number: 35, name: "Habakkuk", book: "Old Testament", author: "Habakkuk" },
  { number: 36, name: "Zephaniah", book: "Old Testament", author: "Zephaniah" },
  { number: 37, name: "Haggai", book: "Old Testament", author: "Haggai" },
  { number: 38, name: "Zechariah", book: "Old Testament", author: "Zechariah" },
  { number: 39, name: "Malachi", book: "Old Testament", author: "Malachi" },
  { number: 40, name: "Matthew", book: "New Testament", author: "Matthew" },
  { number: 41, name: "Mark", book: "New Testament", author: "Mark" },
  { number: 42, name: "Luke", book: "New Testament", author: "Luke" },
  { number: 43, name: "John", book: "New Testament", author: "John" },
  { number: 44, name: "Acts", book: "New Testament", author: "Luke" },
  { number: 45, name: "Romans", book: "New Testament", author: "Paul" },
  { number: 46, name: "1 Corinthians", book: "New Testament", author: "Paul" },
  { number: 47, name: "2 Corinthians", book: "New Testament", author: "Paul" },
  { number: 48, name: "Galatians", book: "New Testament", author: "Paul" },
  { number: 49, name: "Ephesians", book: "New Testament", author: "Paul" },
  { number: 50, name: "Philippians", book: "New Testament", author: "Paul" },
  { number: 51, name: "Colossians", book: "New Testament", author: "Paul" },
  {
    number: 52,
    name: "1 Thessalonians",
    book: "New Testament",
    author: "Paul",
  },
  {
    number: 53,
    name: "2 Thessalonians",
    book: "New Testament",
    author: "Paul",
  },
  { number: 54, name: "1 Timothy", book: "New Testament", author: "Paul" },
  { number: 55, name: "2 Timothy", book: "New Testament", author: "Paul" },
  { number: 56, name: "Titus", book: "New Testament", author: "Paul" },
  { number: 57, name: "Philemon", book: "New Testament", author: "Paul" },
  {
    number: 58,
    name: "Hebrews",
    book: "New Testament",
    author: "Unknown (traditionally attributed to Paul)",
  },
  { number: 59, name: "James", book: "New Testament", author: "James" },
  { number: 60, name: "1 Peter", book: "New Testament", author: "Peter" },
  { number: 61, name: "2 Peter", book: "New Testament", author: "Peter" },
  { number: 62, name: "1 John", book: "New Testament", author: "John" },
  { number: 63, name: "2 John", book: "New Testament", author: "John" },
  { number: 64, name: "3 John", book: "New Testament", author: "John" },
  { number: 65, name: "Jude", book: "New Testament", author: "Jude" },
  { number: 66, name: "Revelation", book: "New Testament", author: "John" },
];
